version: '3.9'

services:
  postgres:
    image: postgres:16.3
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5431:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2-alpine
    restart: always
    ports:
      - 6379:6379

  # bank-management-service:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: bank-management-service
  #   volumes:
  #     - ./:/app
  #   depends_on:
  #     - postgres
  #     - redis
  #   ports:
  #     - 8080:8080

volumes:
  postgres_data:
